version: 2.1

orbs:
  win: circleci/windows@2.4.0 # ✅ Import the Windows orb

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

jobs:
  build:
    executor: win/default # ✅ Use Windows Orb executor
    steps:
      - checkout
      - run:
          name: Install .NET SDK
          command: choco install dotnet-sdk --pre -y --force --verbose
      - run:
          name: Build the project
          command: dotnet build --configuration Release
      - run:
          name: Publish the project
          command: dotnet publish --configuration Release --runtime win-x64 --self-contained false
      - persist_to_workspace:
          root: bin\Release\net9.0\win-x64\publish
          paths:
            - "*"

  deploy:
    executor: win/default # ✅ Use same Windows executor
    steps:
      - attach_workspace:
          at: C:\LottoDataWorker
      - run:
          name: Stop Service
          command: |
            Stop-Service -Name LottoDataService -ErrorAction SilentlyContinue
      - run:
          name: Deploy to Service
          command: |
            Copy-Item -Path "C:\LottoDataWorker\*" -Destination "D:\programs\LottoDataWorker\Deploy\LottoDataService" -Recurse -Force
      - run:
          name: Start Service
          command: Start-Service -Name LottoDataService
