version: 2.1

jobs:
  build:
    executor: windows/default # ✅ Use CircleCI's Windows executor
    steps:
      - checkout
      - run:
          name: Install .NET SDK
          command: choco install dotnet-sdk --version=9.0 -y
      - run:
          name: Build the project
          command: dotnet build --configuration Release
      - run:
          name: Publish the project
          command: dotnet publish --configuration Release --runtime win-x64 --self-contained false
      - persist_to_workspace:
          root: bin\Release\net9.0\win-x64\publish
          paths:
            - "*"

  deploy:
    executor: windows/default # ✅ Use same Windows executor for deployment
    steps:
      - attach_workspace:
          at: C:\LottoDataWorker
      - run:
          name: Stop Service
          command: |
            Stop-Service -Name LottoDataService -ErrorAction SilentlyContinue
      - run:
          name: Deploy to Service
          command: |
            Copy-Item -Path "C:\LottoDataWorker\*" -Destination "D:\programs\LottoDataWorker\Deploy\LottoDataService" -Recurse -Force
      - run:
          name: Start Service
          command: Start-Service -Name LottoDataService

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
